const express = require('express');
const controller = require('../controllers/studentController');
const asyncHandler = require('../middlewares/asyncHandler');

const router = express.Router();
router.get('/', asyncHandler(controller.dashboard));
router.get('/courses', asyncHandler(controller.courses));
router.get('/courses/:enrollmentId', asyncHandler(controller.course));
router.get('/class-meetings/:id', asyncHandler(controller.classMeeting));
router.get('/courses/:enrollmentId/learn', asyncHandler(controller.learn));
router.get('/courses/:enrollmentId/lessons/:lessonId', asyncHandler(controller.lesson));
router.post('/courses/:enrollmentId/lessons/:lessonId/complete', asyncHandler(controller.completeLesson));
router.post('/courses/:enrollmentId/lessons/:lessonId/uncomplete', asyncHandler(controller.uncompleteLesson));
router.get('/courses/:enrollmentId/resources/:publicId', asyncHandler(controller.privateLearningResource));
router.post('/courses/:enrollmentId/lessons/:lessonId/activity', asyncHandler(controller.lessonActivity));
router.get('/schedule', asyncHandler(controller.schedule));
router.get('/payments', asyncHandler(controller.payments));
router.get('/profile', asyncHandler(controller.profile));
router.post('/profile', asyncHandler(controller.updateProfile));
router.post('/profile/password', asyncHandler(controller.updatePassword));
module.exports = router;
