const TRIAL_LIMIT = 5;
const PARTIAL_ACCESS_LIMIT = 10;
const TOTAL_SESSIONS_LIMIT = 16;
const OCCUPYING_ENROLLMENT_STATUSES = ['TRIAL_ACTIVE', 'PLACEMENT_TEST_REQUIRED', 'PAYMENT_REQUIRED', 'CONFIRMED'];
const NON_OCCUPYING_ENROLLMENT_STATUSES = ['CANCELLED', 'PAYMENT_FAILED'];

module.exports = {
  TRIAL_LIMIT,
  PARTIAL_ACCESS_LIMIT,
  TOTAL_SESSIONS_LIMIT,
  OCCUPYING_ENROLLMENT_STATUSES,
  NON_OCCUPYING_ENROLLMENT_STATUSES,
};
