const TRIAL_LIMIT = 3;
const OCCUPYING_ENROLLMENT_STATUSES = ['TRIAL_ACTIVE', 'PLACEMENT_TEST_REQUIRED', 'PAYMENT_REQUIRED', 'CONFIRMED'];
const NON_OCCUPYING_ENROLLMENT_STATUSES = ['CANCELLED', 'PAYMENT_FAILED'];

module.exports = {
  TRIAL_LIMIT,
  OCCUPYING_ENROLLMENT_STATUSES,
  NON_OCCUPYING_ENROLLMENT_STATUSES,
};
