ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'CERTIFICATE_AVAILABLE';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'CERTIFICATE_PAYMENT_REQUIRED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'CERTIFICATE_PAYMENT_CONFIRMED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'CERTIFICATE_FEE_WAIVED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'CERTIFICATE_ISSUED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'CERTIFICATE_REVOKED';
CREATE TYPE "CertificatePaymentStatus" AS ENUM ('PENDING','CONFIRMED','FAILED','CANCELLED');
CREATE TYPE "CertificateStatus" AS ENUM ('ISSUED','REVOKED');
ALTER TABLE "courses" ADD COLUMN "certificate_fee" DECIMAL(10,2);
ALTER TABLE "training_sessions" ADD COLUMN "certificate_fee" DECIMAL(10,2);
CREATE TABLE "certificate_settings" ("id" INTEGER NOT NULL DEFAULT 1 PRIMARY KEY, "certificates_paid" BOOLEAN NOT NULL DEFAULT false, "general_amount" DECIMAL(10,2) NOT NULL DEFAULT 0, "currency" TEXT NOT NULL DEFAULT 'USD', "updated_at" TIMESTAMP(3) NOT NULL);
INSERT INTO "certificate_settings" ("id","certificates_paid","general_amount","currency","updated_at") VALUES (1,false,0,'USD',CURRENT_TIMESTAMP);
CREATE TABLE "certificate_requests" ("id" SERIAL PRIMARY KEY, "enrollment_id" INTEGER NOT NULL, "is_fee_waived" BOOLEAN NOT NULL DEFAULT false, "fee_waived_by_admin_id" INTEGER, "fee_waived_at" TIMESTAMP(3), "fee_waiver_reason" TEXT, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL);
CREATE UNIQUE INDEX "certificate_requests_enrollment_id_key" ON "certificate_requests"("enrollment_id");
CREATE INDEX "certificate_requests_fee_waived_by_admin_id_idx" ON "certificate_requests"("fee_waived_by_admin_id");
ALTER TABLE "certificate_requests" ADD CONSTRAINT "certificate_requests_enrollment_id_fkey" FOREIGN KEY ("enrollment_id") REFERENCES "enrollments"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "certificate_requests" ADD CONSTRAINT "certificate_requests_fee_waived_by_admin_id_fkey" FOREIGN KEY ("fee_waived_by_admin_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
CREATE TABLE "certificate_payments" ("id" SERIAL PRIMARY KEY, "student_id" INTEGER NOT NULL, "enrollment_id" INTEGER NOT NULL, "amount" DECIMAL(10,2) NOT NULL, "currency" TEXT NOT NULL, "status" "CertificatePaymentStatus" NOT NULL DEFAULT 'PENDING', "payment_method" TEXT NOT NULL, "reference" TEXT NOT NULL, "confirmed_at" TIMESTAMP(3), "confirmed_by_admin_id" INTEGER, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL);
CREATE UNIQUE INDEX "certificate_payments_reference_key" ON "certificate_payments"("reference");
CREATE INDEX "certificate_payments_enrollment_id_status_idx" ON "certificate_payments"("enrollment_id","status");
CREATE INDEX "certificate_payments_student_id_idx" ON "certificate_payments"("student_id");
ALTER TABLE "certificate_payments" ADD CONSTRAINT "certificate_payments_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "certificate_payments" ADD CONSTRAINT "certificate_payments_enrollment_id_fkey" FOREIGN KEY ("enrollment_id") REFERENCES "enrollments"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "certificate_payments" ADD CONSTRAINT "certificate_payments_confirmed_by_admin_id_fkey" FOREIGN KEY ("confirmed_by_admin_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
CREATE TABLE "certificates" ("id" SERIAL PRIMARY KEY, "certificate_request_id" INTEGER NOT NULL, "serial_number" TEXT NOT NULL, "status" "CertificateStatus" NOT NULL DEFAULT 'ISSUED', "issued_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "issued_by_admin_id" INTEGER NOT NULL, "revoked_at" TIMESTAMP(3), "revoked_by_admin_id" INTEGER, "revocation_reason" TEXT);
CREATE UNIQUE INDEX "certificates_certificate_request_id_key" ON "certificates"("certificate_request_id");
CREATE UNIQUE INDEX "certificates_serial_number_key" ON "certificates"("serial_number");
CREATE INDEX "certificates_status_idx" ON "certificates"("status");
ALTER TABLE "certificates" ADD CONSTRAINT "certificates_certificate_request_id_fkey" FOREIGN KEY ("certificate_request_id") REFERENCES "certificate_requests"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "certificates" ADD CONSTRAINT "certificates_issued_by_admin_id_fkey" FOREIGN KEY ("issued_by_admin_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "certificates" ADD CONSTRAINT "certificates_revoked_by_admin_id_fkey" FOREIGN KEY ("revoked_by_admin_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
